### ISSUE TITLE
example is outdated

### ISSUE THREAD

**Issue by PavelPolyakov** [hapijs/reptile#21]
I think example server is outdated.

I have changed it to this variant:
```javascript
var Hapi = require('hapi');
var Reptile = require('../');


var server = new Hapi.Server();

server.connection({ 
    host: 'localhost', 
    port: 8000 
});

server.register([{ register: Reptile }], function (err) {

    if (err) {
        console.error(err);
        process.exit(1);
    }

    console.log('REPL available on port 9000');
});

server.start(function () {

    console.log('Server started at http://localhost:' + server.info.port);
});

```

Currently the server starts, but I can not do anything on the port ```9000```.

![image](https://cloud.githubusercontent.com/assets/839290/10593119/408ee0ae-76c1-11e5-9aff-db4d9ea79115.png)

Does this plugin still supported and wokring? Tried with hapi 10.5.0.

Regards,

**Comment by geek** [comment]
@PavelPolyakov yes, please submit at PR.  Thanks.

**Comment by PavelPolyakov** [comment]
@geek 

PR would not be an issue, but even if server is started, I am not able to telnet 9000 port, so I think the case is somewhere in the other place, as well.
