### ISSUE TITLE
Peer dependency with hapi disallows v11 and v12

### ISSUE THREAD

**Issue by devinivy** [hapijs/reptile#31]
Turns out the change made to resolve #29 wasn't necessary and ended-up breaking usage with hapi v11 and v12 (`npm install` fails with a peer-dependency error).  I feel sure it wasn't intended to be a breaking change.  Just reverting the peer deps of hapi from `13.x.x` back to `>=11.x.x` should do the trick!

**Comment by geek** [comment]
@devinivy thanks, I have it resolved now.
