### ISSUE TITLE
Reptile@3.0.0 missing 'lib' folder

### ISSUE THREAD

**Issue by swaj** [hapijs/reptile#39]
When downloading the latest release of Reptile (3.0.0) from npm, I've noticed the tarball is missing the `lib` folder when downloaded.

```
$ curl -O `npm --registry=https://registry.npmjs.org/ info reptile dist.tarball`
$ tar xf reptile-3.0.0.tgz
$ ls ./package/
total 24
-rwxr-xr-x  1 scott  scott  1655 Jan  6  2017 LICENSE*
-rw-r--r--  1 scott  scott   756 Jan  6  2017 README.md
-rw-r--r--  1 scott  scott   672 Nov 16 16:29 package.json
```

It looks like the version published somehow missed the `lib` folder, so when you `require('reptile')` it doesn't work.

**Comment by geek** [comment]
@swaj thanks, this is now fixed in v3.0.1
